# Generated by Django 2.2 on 2020-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDojoReads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
