# Generated by Django 2.2 on 2020-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneTable', '0002_prisoner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prisoner',
            old_name='dungeon_inside',
            new_name='dungeon',
        ),
        migrations.RenameField(
            model_name='prisoner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='prisoner',
            name='last_name',
            field=models.TextField(null=True),
        ),
    ]
