# Generated by Django 2.2 on 2020-03-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books_author',
            field=models.ManyToManyField(related_name='authors_book', to='books_authors_app.Book'),
        ),
    ]
